Squashed commit of the following:
commit dd3cc4e16135f4d7fd413d2d17dc9f0866950c24
Author: P2654585 <P2654585@my365.dmu.ac.uk>
Date:   Thu Mar 9 11:32:58 2023 +0000

    Update Affine Cipher P2654585.py

commit 28edd0e018c51dc8378d2cbbfaeeb6b65c9b063d
Merge: c7e9b48 39b1f33
Author: P2654585 <P2654585@my365.dmu.ac.uk>
Date:   Thu Mar 9 11:32:26 2023 +0000

    Update README.md

commit c7e9b4814889c74c8dc41f2bd198ee81d8309879
Author: P2654585 <P2654585@my365.dmu.ac.uk>
Date:   Thu Mar 9 11:27:52 2023 +0000

    Latest complete revision of program

    bruteforce algorithm is complete.
    allow user to raw bruteforce or sort output.

    heavy commented program.

commit 268727fe7bcbfa0de37cdfeffae2eced3accc7e9
Author: P2654585 <P2654585@my365.dmu.ac.uk>
Date:   Thu Feb 23 11:49:13 2023 +0000

    Added Frequency analysis

    Added Frequency analysis to predict the probability of the answer

    very rough

commit 48e75dc043e065f598e72c60ce13c3263d96cc75
Author: P2654585 <P2654585@my365.dmu.ac.uk>
Date:   Sun Feb 5 15:11:15 2023 +0000

    Implemented Bruteforce algorithm

    60-70% of coursework achieved

commit 053a02cd1f2e18624b4bb18de42c679841603dc9
Author: P2654585 <P2654585@my365.dmu.ac.uk>
Date:   Wed Feb 1 22:16:22 2023 +0000

    bruteforce test 1

        affine_output = ((multiplicative_Inverse*(y-key_b)) % 26)
                          ~~~~~~~~~~~~~~~~~~~~~~^^~~~~~~~~
    TypeError: unsupported operand type(s) for *: 'NoneType' and 'int'